language: go

go:
  - 1.x

before_install:
  - go get -v github.com/golang/lint/golint

script:
  - go test -v ./...
  - golint ./...
  - go vet ./...
  - gofmt -d -e -s ./
  - go test -cover -coverprofile=coverage.out
